name: DankTitles
main: com.karus.danktitles.DankTitles
version: 1.0.1
description: Create dank titles for players
author: PanteLegacy
depend: [Vault]
commands:
  danktitles:
    description: Use this command to check the version number and reload the plugin.
    usage: "|
        /DankTitles
        /DankTitles [<about|help|reload|save>]
        /DankTitles [<player>] [<add|remove|reset>] [<category>] [<title>]"
    aliases: [dt, dtitles]
permissions:
  danktitles.*:
    description: Gives access to all danktitles commands.
  danktitles.about:
    description: Allows players to view the version of the plugin
    default: op
  danktitles.help:
    description: Allows players to view a list of plugin commands
    default: not op
  danktitles.reload:
    description: Allows players to force-reload the plugin
    default: op
  danktitles.reset:
    description: Allows players to reset their titles back to their group defaults
    default: not op  
  danktitles.save:
    description: Allows players to force-save the plugin
    default: op
  danktitles.titles:
    description: Allows players to open a GUI menu of all the titles they own
    default: not op
  danktitles.add:
    description: Allows access to giving a player a title that is defined in titles.yml
    default: op
  danktitles.remove:
    description: Allows access to removing a player's title defined in players.yml
    default: op
