name: DankTitles
main: com.karus.danktitles.DankTitles
version: 1.0.0
description: Create your own endless list of Dank Titles
author: PanteLegacy
depend: [Vault]
commands:

  danktitles:
    aliases: [dt, dtitles]
    description: Use this to add titles and whatnot
    usage: /DankTitles [subcommand]
    permission: danktitles.command
  
  about:
    aliases: [about]
    description: Allows administrators to view the plugin version and information
    usage: /DankTitles about
    permission: danktitles.about
  
  add:
    aliases: [add, give]
    description: Adds a titles to the player
    usage: /DankTitles add [category] [title] (<name|UUID>)
    permission: danktitles.add
  
  help:
    aliases: [help, h]
    description: Allows players to view the list of commands
    usage: /DankTitles help [(all|subcommand)] [(page number)]
    permission: danktitles.help
    
  menu:
    aliases: [menu, m]
    description: Opens up the menu for selecting a title
    usage: /DankTitles menu
    permission: danktitles.menu
    
  reload:
    aliases: [reload, load]
    description: Reloads the plugin files
    usage: /DankTitles reload [component]
    permission: danktitles.reload
  
  remove:
    aliases: [remove, delete, del]
    description: Removes the players title
    usage: /DankTitles remove [category] [title] (<name|UUID>)
    permission: danktitles.remove
  
  save:
    aliases: [save]
    description: Saves the plugin data to files
    usage: /DankTitles save [component]
    permission: danktitles.save
  
  set:
    aliases: [set]
    description: Sets the specified player's title
    usage: /DankTitles set (category) (title) (<name|UUID>)
    permission: danktitles.set
  
permissions:
  danktitles.*:
    description: Gives access to all DankTitles commands.
    children:
      danktitles.command: true
      danktitles.about: true
      danktitles.add: true
      danktitles.help: true
      danktitles.menu: true
      danktitles.reload: true
      danktitles.remove: true
      danktitles.save: true
      danktitles.set: true
     
  danktitles.command:
    default: false
    
  danktitles.about:
    default: false
  
  danktitles.add:
    default: false
    
  danktitles.help:
    default: false
    
  danktitles.menu:  
    default: false
    
  danktitles.reload:
    default: false
    
  danktitles.remove:
    default: false
    
  danktitles.save:
    default: false
    
  danktitles.set:
    default: false
