name: DankTitles
main: com.karus.danktitles.DankTitles
version: 1.0.0
description: Create dank titles for players
author: PanteLegacy
depend: [Vault]
commands:
  danktitles:
    description: Use this command to check the version number and reload the plugin.
    usage: |
      /DankTitles
      /DankTitles [<about|help|reload>]
      /DankTitles [<add|remove>] [<category>] [<title>] [<player>]
    aliases: [dt]
permissions:
  danktitles.*:
    description: Gives access to all danktitles commands.
    children:
      danktitles.about: true
      danktitles.help: true
      danktitles.reload: true
      danktitles.titles: true
      danktitles.add: true
      danktitles.remove: true
  danktitles.about:
    description: Allows players to view the version of the plugin
    default: not op
  danktitles.help:
    description: Allows players to view a list of plugin commands
    default: not op
  danktitles.titles:
    description: Allows players to open a GUI menu of all the titles they own
    default: not op
  danktitles.add:
    description: Allows access to giving a player a title that is defined in titles.yml
    default: op
  danktitles.remove:
    description: Allows access to removing a player's title defined in players.yml
    default: op
